---
- name: Configure ACLS
  hosts: routers
  gather_facts: no
  
  vars_files:
    - acl_var.yml
    - if_var.yml
    - ntp_var.yml
    - banner_vars.yml
    
  tasks:
    - name: Delete ACLs IOSXE
      ios_acls:
        config: "{{acl}}"
        state: deleted
      when: ('ios' in ansible_network_os) 

    - name: Delete Loopback interface IOSXE
      ios_l3_interfaces:
        config: "{{l3_interface}}"
        state: deleted
      when: ('ios' in ansible_network_os) and l3_interface is defined
      
    - name: Delete Loopback interface EOS
      eos_l3_interfaces:
        config: "{{l3_interface}}"
        state: deleted
      when: ('eos' in ansible_network_os) and l3_interface is defined

    - name: Delete IOS system properties onto device
      ios_system:
        domain_name: "{{network_domain_name | default(omit, True) }}"
        domain_search: "{{network_domain_search | default(omit, True)}}"
        lookup_source: "{{network_lookup_source | default(omit, True) }}"
        name_servers: "{{network_name_servers | default(omit, True) }}"
        state: absent
      when: ('ios' in ansible_network_os) or network_domain_name is defined or network_domain_search is defined or network_lookup_source is defined or network_name_servers is defined

    - name: Delete EOS system properties onto device
      eos_system:
        domain_name: "{{network_domain_name | default(omit, True) }}"
        domain_search: "{{network_domain_search | default(omit, True)}}"
        lookup_source: "{{network_lookup_source | default(omit, True) }}"
        name_servers: "{{network_name_servers | default(omit, True) }}"
        state: absent
      when: ('eos' in ansible_network_os) or network_domain_name is defined or network_domain_search is defined or network_lookup_source is defined or network_name_servers is defined

    - name: Remove NTP IOSXE
      ios_config:
        lines: "no ntp server {{ntp_server}}"
      when: ('ios' in ansible_network_os) and ntp_server is defined

    - name: Remove NTP EOS
      eos_config:
        lines: "no ntp server {{ntp_server}}"
      when: ('eos' in ansible_network_os) and ntp_server is defined

    - name: Remove management user IOSXE
      ios_user:
        name: "{{network_name | default(omit, True) }}"
        ssh_key: "{{network_key | default(omit, True) }}"
        privilege: "{{network_privilege | default(omit, True) }}"
        configured_password: "{{network_configured_password | default(omit, True) }}"
        state: absent
      when: ('ios' in ansible_network_os) and network_name is defined
      
    - name: Remove management user EOS
      eos_user:
        name: "{{network_name | default(omit, True) }}"
        ssh_key: "{{network_key | default(omit, True) }}"
        privilege: "{{network_privilege | default(omit, True) }}"
        configured_password: "{{network_configured_password | default(omit, True) }}"
        state: absent
      when: ('eos' in ansible_network_os) and network_name is defined   
        
    - name: Add banner IOSXE
      ios_banner:
        text: "{{ network_banner }}"
        banner: "{{ banner_type }}"
        state: deleted
      when: ('ios' in ansible_network_os) and network_banner is defined
      
    - name: Add banner EOS
      eos_banner:
        text: "{{ network_banner }}"
        banner: "{{ banner_type }}"
        state: deleted
      when: ('eos' in ansible_network_os) and network_banner is defined 
